# Generated by Django 4.1.7 on 2023-02-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_review_stadium_delete_choice_delete_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='aveaccessrating',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='avefoodrating',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='avepassionrating',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='avetotalrating',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='avevisibilityrating',
        ),
    ]
